package com.pnc.book.store.app;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2021-04-08T12:15:56.157-05:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://www.pnc.com/book/store/app", name = "BookStorePort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BookStorePort {

    @WebMethod(operationName = "GetBook")
    @WebResult(name = "GetBookResponse", targetNamespace = "http://www.pnc.com/book/store/app", partName = "GetBookResponse")
    public GetBookResponse getBook(
        @WebParam(partName = "GetBookRequest", name = "GetBookRequest", targetNamespace = "http://www.pnc.com/book/store/app")
        GetBookRequest getBookRequest
    );

    @WebMethod(operationName = "AddBook")
    @WebResult(name = "AddBookResponse", targetNamespace = "http://www.pnc.com/book/store/app", partName = "AddBookResponse")
    public AddBookResponse addBook(
        @WebParam(partName = "AddBookRequest", name = "AddBookRequest", targetNamespace = "http://www.pnc.com/book/store/app")
        AddBookRequest addBookRequest
    );

    @WebMethod(operationName = "GetAllBooks")
    @WebResult(name = "GetAllBooksResponse", targetNamespace = "http://www.pnc.com/book/store/app", partName = "GetAllBooksResponse")
    public GetAllBooksResponse getAllBooks(
        @WebParam(partName = "GetAllBooksRequest", name = "GetAllBooksRequest", targetNamespace = "http://www.pnc.com/book/store/app")
        GetAllBooksRequest getAllBooksRequest
    );
}
